# tier2_logic_1gateway/main.py
# Command to run: python -m uvicorn tier2_logic_1gateway.main:app --reload
# http://127.0.0.1:8000/docs

import json
from fastapi import FastAPI, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager
from tortoise import Tortoise


# Import local modules (Current monolithic deployment)
from tier2_logic_2calculation.us_calculator import calculate_us_order
from tier2_logic_2calculation.jp_calculator import calculate_jp_order


# Database Lifecycle (Required for local monolith)
@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Manages database connections for the current single-server architecture.
    """
    await Tortoise.init(
        db_url='sqlite://tier3_data/db.sqlite3',
        modules={'models': ['tier2_logic_3data.models']},
        _enable_global_fallback=True,
    )
    yield
    await Tortoise.close_connections()

app = FastAPI(title="Distributed Bookstore API Gateway", lifespan=lifespan)


# CORS Configuration (Crucial for Frontend)
# This allows local HTML/JS to communicate with this backend API.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],      # Allow all origins (for local development only)
    allow_credentials=True,
    allow_methods=["*"],      # Allow all HTTP methods (POST, GET, etc.)
    allow_headers=["*"],      # Allow all headers
)

# Route Dispatch Registry (The Gateway Core)

# FUTURE PROOFING: 
# When US and JP move to different servers, please ONLY change this table.
# Please replace the local function calls with HTTP clients
# that forward the raw_json_string to "http://us-server-ip/api/calculate" something like that.
DISPATCH_TABLE = {
    "US": calculate_us_order,
    "JP": calculate_jp_order
}


# API Endpoints
@app.get("/")
async def welcome():
    """Health check endpoint."""
    return {"message": "Gateway is online and routing traffic.", "status": "Online"}

@app.post("/api/calculate")
async def unified_gateway(request: Request):
    """
    Unified Endpoint: Acts as a pure reverse proxy dispatcher.
    It reads the JSON, finds the routing key ('region'), and dispatches the raw payload.
    """
    # 1. Intercept the RAW HTTP body as bytes, then decode to string
    raw_body_bytes = await request.body()
    raw_json_string = raw_body_bytes.decode("utf-8")
    
    # 2. Minimal inspection to find the routing key
    try:
        data = json.loads(raw_json_string)
        region = data.get("region", "").upper()
    except json.JSONDecodeError:
        error_res = '{"status": "failed", "errors": [{"error_code": "E000", "message": "Invalid JSON"}]}'
        return Response(content=error_res, media_type="application/json", status_code=400)

    # 3. Route Dispatching using the Registry
    target_handler = DISPATCH_TABLE.get(region)
    
    if not target_handler:
        # Reject if the region is missing or unknown
        error_res = '{"status": "failed", "errors": [{"error_code": "E999", "message": "Unknown region"}]}'
        return Response(content=error_res, media_type="application/json", status_code=400)

    # 4. Forward the RAW payload to the assigned handler (Local or Remote)
    result_json_string = await target_handler(raw_json_string)

    # 5. Return the exact string generated by the target server without re-encoding
    return Response(content=result_json_string, media_type="application/json")